name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter packages get
    - name: Format Code
      run: flutter format --set-exit-if-changed .
    - name: Analyze Code
      run: flutter analyze .
    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
